[avif.oavif]
requires = "oavif"
command = [
    "oavif",
    "-s",
    "{{ speed }}",       # 0 (slowest) to 10 (fastest)
    "-t",
    "{{ quality }}",     # 0 to 100
    "{{ input_path }}",
    "{{ output_path }}",
]
args = { speed = "1", quality = "80" }

[avif.magick]
requires = "magick"
command = [
    "magick",
    "{{ input_path }}",
    "-depth",
    "10",
    "-define",
    "heic:chroma=444",
    "-define",
    "heic:speed={{ speed }}", # 0 (slowest) to 10 (fastest)
    "-quality",
    "{{ quality }}",          # 0 to 100
    "{{ output_path }}",
]
args = { speed = "1", quality = "70" }

[avif.ffmpeg]
requires = "ffmpeg"
command = [
    "ffmpeg",
    "-hide_banner",
    "-y",
    "-i",
    "{{ input_path }}",
    "-c:v",
    "libaom-av1",
    "-cpu-used",
    "{{ speed }}",       # 0 (slowest) to 10 (fastest)
    "-b:v",
    "0",
    "-crf",
    "{{ quality }}",     # 0 (best) to 63 (worst)
    "-pix_fmt",
    "yuv444p10le",
    "-color_range",
    "pc",
    "-still-picture",
    "1",
    "-aom-params",
    "tune=iq",
    "{{ output_path }}",
]
args = { speed = "1", quality = "24" }

[avif.avifenc]
requires = "avifenc"
command = [
    "avifenc",
    "--codec",
    "aom",
    "--speed",
    "{{ speed }}",       # 0 (slowest) to 10 (fastest)
    "--jobs",
    "all",
    "--depth",
    "10",
    "--yuv",
    "444",
    "--qcolor",
    "{{ quality }}",     # 0 to 100
    "--advanced",
    "tune=iq",
    "{{ input_path }}",
    "{{ output_path }}",
]
args = { speed = "1", quality = "68" }

[webp.magick]
requires = "magick"
command = [
    "magick",
    "{{ input_path }}",
    "-define",
    "webp:method={{ speed }}", # 0 (fastest) to 6 (slowest)
    "-quality",
    "{{ quality }}",           # 0 to 100
    "{{ output_path }}",
]
args = { speed = "6", quality = "84" }
